name: wholesale_billing_app
description: Wholesale Billing App v6 scaffold
publish_to: 'none'
version: 0.6.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.3.3+1
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0
  speech_to_text: ^7.3.0
  excel: ^4.0.6
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
