class AppConstants {
  static const appName = 'Wholesale Billing App';

  static const invoiceTypes = ['Cash', 'Lakshmi Traders', 'UPI', 'Wholesale'];
  static const units = ['kg', 'g', 'ltr', 'pcs'];

  static const defaultCustomers = [
    'Cash',
    'Lakshmi Traders',
    'Ramesh Kirana',
    'Sai Traders',
  ];

  static const noiseWords = [
    'amma',
    'anna',
    'sir',
    'madam',
    'please',
    'ok',
    'okay',
    'hello',
    'test',
    'add',
    'give',
    'take',
    'next',
    'and',
    'aur',
    'mariyu',
    'mattu',
    'phir',
    'tarvata',
    'aamele',
  ];

  static const itemAliases = {
    'Rice': [
      'rice',
      'biyyam',
      'akki',
      'chawal',
      'राइस',
      'चावल',
      'బియ్యం',
      'రైస్',
      'ಅಕ್ಕಿ',
      'ರೈಸ್',
    ],
    'Sugar': [
      'sugar',
      'cheeni',
      'panchadara',
      'sakkare',
      'शुगर',
      'चीनी',
      'शक्कर',
      'చక్కెర',
      'షుగర్',
      'ಸಕ್ಕರೆ',
    ],
    'Toor Dal': [
      'toor dal',
      'tur dal',
      'dal',
      'daal',
      'kandi pappu',
      'arhar dal',
      'togari bele',
      'दाल',
      'तूर दाल',
      'अरहर दाल',
      'పప్పు',
      'కందిపప్పు',
      'ಬೇಳೆ',
      'ತೊಗರಿ ಬೇಳೆ',
    ],
    'Oil': [
      'oil',
      'nune',
      'tel',
      'enne',
      'तेल',
      'నూనె',
      'ಎಣ್ಣೆ',
    ],
    'Tamarind': [
      'tamarind',
      'tamrin',
      'imli',
      'chintapandu',
      'hunasehannu',
      'इमली',
      'చింతపండు',
      'ಹುಣಸೆಹಣ್ಣು',
    ],
    'Salt': [
      'salt',
      'namak',
      'uppu',
      'नमक',
      'ఉప్పు',
      'ಉಪ್ಪು',
    ],
    'Milk': [
      'milk',
      'doodh',
      'paalu',
      'haalu',
      'दूध',
      'పాలు',
      'ಹಾಲು',
    ],
    'Curd': [
      'curd',
      'dahi',
      'perugu',
      'mosaru',
      'दही',
      'పెరుగు',
      'ಮೊಸರು',
    ],
    'Atta': [
      'atta',
      'aata',
      'wheat flour',
      'आटा',
      'పిండి',
      'ಹಿಟ್ಟು',
    ],
    'Chips': [
      'chips',
      'chip',
      'packet chips',
      'चिप्स',
      'చిప్స్',
      'ಚಿಪ್ಸ್',
    ],
    'Tea Powder': [
      'tea powder',
      'tea',
      'chai patti',
      'चाय पत्ती',
      'టీ పొడి',
      'ಟೀ ಪುಡಿ',
    ],
    'Coffee Powder': [
      'coffee powder',
      'coffee',
      'कॉफी',
      'కాఫీ',
      'ಕಾಫಿ',
    ],
    'Biscuits': [
      'biscuits',
      'biscuit',
      'बिस्किट',
      'బిస్కెట్',
      'ಬಿಸ್ಕಟ್',
    ],
    'Soap': [
      'soap',
      'sabun',
      'साबुन',
      'సబ్బు',
      'ಸಾಬೂನು',
    ],
    'Detergent': [
      'detergent',
      'surf',
      'washing powder',
      'डिटर्जेंट',
      'సర్ఫ్',
      'ಡಿಟರ್ಜೆಂಟ್',
    ],
  };

  static const itemDefaults = {
    'Rice': {'unit': 'kg', 'rate': 52.0},
    'Sugar': {'unit': 'kg', 'rate': 45.0},
    'Toor Dal': {'unit': 'kg', 'rate': 130.0},
    'Oil': {'unit': 'ltr', 'rate': 120.0},
    'Tamarind': {'unit': 'kg', 'rate': 160.0},
    'Salt': {'unit': 'kg', 'rate': 20.0},
    'Milk': {'unit': 'ltr', 'rate': 28.0},
    'Curd': {'unit': 'ltr', 'rate': 40.0},
    'Atta': {'unit': 'kg', 'rate': 38.0},
    'Chips': {'unit': 'pcs', 'rate': 20.0},
    'Tea Powder': {'unit': 'pcs', 'rate': 80.0},
    'Coffee Powder': {'unit': 'pcs', 'rate': 120.0},
    'Biscuits': {'unit': 'pcs', 'rate': 10.0},
    'Soap': {'unit': 'pcs', 'rate': 35.0},
    'Detergent': {'unit': 'pcs', 'rate': 95.0},
  };
}